"""
Django settings for course4_proj project.

Generated by 'django-admin startproject' using Django 3.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os

from configurations import Configuration
from configurations import values
from pathlib import Path

class Dev(Configuration):
        # Build paths inside the project like this: BASE_DIR / 'subdir'.
        BASE_DIR = Path(__file__).resolve().parent.parent


        # Quick-start development settings - unsuitable for production
        # See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

        # SECURITY WARNING: keep the secret key used in production secret!
        SECRET_KEY = 'django-insecure-zaiqyyg8b%h58-f)dga!6sgs$tkk1qi*m_$gv=w=%_3)pdj@e@'
        # OMDB_KEY = values.SecretValue()
        OMDB_KEY = "cdb7d6b4"
        # the key used is = 'cdb7d6b4'

        # SECURITY WARNING: don't run with debug turned on in production!
        DEBUG = True

        ALLOWED_HOSTS = ['127.0.0.1', 'localhost']

        # X_FRAME_OPTIONS = "ALLOW-FROM " + os.environ.get("CODIO_HOSTNAME") + "-8000.codio.io"
        CSRF_COOKIE_SAMESITE = None
        CSRF_COOKIE_SAMESITE = "None"
        # CSRF_TRUSTED_ORIGINS = [os.environ.get("CODIO_HOSTNAME") + "-8000.codio.io"]
        CSRF_COOKIE_SECURE = True
        SESSION_COOKIE_SECURE = True
        SESSION_COOKIE_SAMESITE = "None"

        CELERY_RESULT_BACKEND = 'django-db'
        CELERY_CACHE_BACKEND = 'django-cache'

        CELERYD_FORCE_EXECV = True  # 🔥 Important line for Windows
        CELERYD_POOL = "solo"  # This makes Celery work on Windows
        CELERY_BROKER_URL = "redis://localhost:6379/0"  # Use Redis URL
        CELERY_ACCEPT_CONTENT = ["json"]
        CELERY_TASK_SERIALIZER = "json"

        # django setting.
        CACHES = {
            'default': {
                'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
                'LOCATION': 'my_cache_table',
            }
        }
        # Application definition

        THIRD_PARTY_APPS = [
            "django_browser_reload",
            'django_celery_results',

        ]
        LOCAL_APPS = [
            'movies',
            'gh',
                      ]
        INSTALLED_APPS = [
            'django.contrib.admin',
            'django.contrib.auth',
            'django.contrib.contenttypes',
            'django.contrib.sessions',
            'django.contrib.messages',
            'django.contrib.staticfiles',

        ]+LOCAL_APPS+THIRD_PARTY_APPS


        MIDDLEWARE = [
            'django.middleware.security.SecurityMiddleware',
            'django.contrib.sessions.middleware.SessionMiddleware',
            'django.middleware.common.CommonMiddleware',
            # 'django.middleware.csrf.CsrfViewMiddleware',
            'django.contrib.auth.middleware.AuthenticationMiddleware',
            'django.contrib.messages.middleware.MessageMiddleware',
            "django_browser_reload.middleware.BrowserReloadMiddleware",
            # 'django.middleware.clickjacking.XFrameOptionsMiddleware',
        ]

        ROOT_URLCONF = 'course4_proj.urls'

        TEMPLATES = [
            {
                'BACKEND': 'django.template.backends.django.DjangoTemplates',
                'DIRS': [],
                'APP_DIRS': True,
                'OPTIONS': {
                    'context_processors': [
                        'django.template.context_processors.debug',
                        'django.template.context_processors.request',
                        'django.contrib.auth.context_processors.auth',
                        'django.contrib.messages.context_processors.messages',
                    ],
                },
            },
        ]

        WSGI_APPLICATION = 'course4_proj.wsgi.application'


        # Database
        # https://docs.djangoproject.com/en/3.2/ref/settings/#databases

        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }


        # Password validation
        # https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

        # AUTH_PASSWORD_VALIDATORS = [
        #     {
        #         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        #     },
        #     {
        #         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        #     },
        #     {
        #         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
        #     },
        #     {
        #         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
        #     },
        # ]


        # Internationalization
        # https://docs.djangoproject.com/en/3.2/topics/i18n/

        LANGUAGE_CODE = 'en-us'

        TIME_ZONE = 'UTC'

        USE_I18N = True

        USE_L10N = True

        USE_TZ = True


        # Static files (CSS, JavaScript, Images)
        # https://docs.djangoproject.com/en/3.2/howto/static-files/

        STATIC_URL = '/static/'

        # Default primary key field type
        # https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

        DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
        LOGGING = {
            "version": 1,
            "disable_existing_loggers": False,
            "formatters": {
                "verbose": {
                    "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
                    "style": "{",
                },
            },
            "handlers": {
                "console": {
                    "class": "logging.StreamHandler",
                    "stream": "ext://sys.stdout",
                    "formatter": "verbose",
                }
            },
            "root": {
                "handlers": ["console"],
                "level": "DEBUG",
            },
        }
class Prod(Dev):
        DEBUG = False